[xdebug]
zend_extension=xdebug
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_port = 9003

; Gọi về máy host (máy đang chạy VS Code)
xdebug.client_host = host.docker.internal

; Bật log để gỡ lỗi 
xdebug.log = /tmp/xdebug.log